### ISSUE TITLE
Discussion on the applicability of other dexterous hands

### ISSUE THREAD

**Issue by JJMa1907** [PKU-EPIC/DexGraspNet2#1]
This work looks great.  I am wondering if it's possible to use other types of dexterous hands for this work, such as allergo hand or shadow hand. If so, could you kindly provide me with any available tutorials?
Thank you very much for your attention and assistance.

**Comment by mzhmxzh** [comment]
Thank you for your interest in our work! 
If you want to create a similar dataset for other dexterous hands, you could try something like retargeting (might be a bit tricky for Shadow Hand since it has five fingers). 
But there's currently no plans in releasing the code for synthesizing the grasps from scratch. So if you wish to create a dataset for another hand using the same algorithm that we used for LEAP hand, you could contact our advisor Prof. Wang for cooperation. 
Personally I think LEAP hand is enough for research, but please don't hesitate if you need further assistance.
